#!/usr/bin/env python

import sys
import asynctools

if __name__ == '__main__':
    if len(sys.argv)>1:
        LABEL = sys.argv[1]
    else:
        print('Usage: async_download <LABEL> <OPTIONAL: start line index> <OPTIONAL: end line index>')
        sys.exit(1)

    START = None
    if len(sys.argv)>2:
        START = int(sys.argv[2])

    END = None
    if len(sys.argv)>3:
        END = int(sys.argv[3])

    downloader = asynctools.AsyncDownloader(LABEL, START, END)  
    downloader.download()
