#!/usr/bin/env python

import sys
import asynctools

if __name__ == '__main__':
    if len(sys.argv) > 4:
        LABEL = sys.argv[1]
        INPUT_FORMAT = sys.argv[2]
        OUTPUT_FORMAT = sys.argv[3]
        MIN_SIZE = int(sys.argv[4])
        MAX_RATIO = float(sys.argv[5])
        resizer = asynctools.AsyncResizer(LABEL, INPUT_FORMAT, OUTPUT_FORMAT, MIN_SIZE, MAX_RATIO)
        resizer.resize()
    else:
        print('Usage: async_resize <LABEL> <INPUT_FORMAT (e.g. png)> <OUTPUT FORMAT (e.g. jpeg)> <MIN SIZE (e.g. 300)> <MAX RATIO (e.g. 2.0)>')
        sys.exit(1)
